

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /
login_login:
    resource: "@LoginLoginBundle/Controller/"
    type:     annotation
    prefix:   /auth




#login_login_signup:
#    resource: "@LoginLoginBundle/Controller/"
#    type:     annotation
#    prefix:   /singup
#

